### ISSUE TITLE
Production use

### ISSUE THREAD

**Issue by ugintl** [RaamAnalyst/JLite-CRM#1]
Is it recommended to be used on production?

**Comment by RaamAnalyst** [comment]
Yes. It is secure as it is based on Laravel 8.

**Comment by ugintl** [comment]
If it is possible, please upload a demo. or else some more snapshots, but demo will be much better.

**Comment by RaamAnalyst** [comment]
Please find the demo of the application in the following link: https://youtu.be/f1vnraoYW3s
